source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use sqlite3 as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

#modals
gem 'bootstrap-sass'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
# gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

#build chosen select multiple
gem 'chosen-rails'

#resize Images
gem "mini_magick"

#Manage nested forms
gem "simple_form"
gem 'cocoon'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

#Admin
gem 'rails_admin', '~> 1.0'

# Annotate models
gem 'annotate'

# HAML
gem 'haml-rails'

# Authentication
gem 'devise'

# Images
gem 'carrierwave'

# Roles
gem 'rolify'

# Filters
gem 'searchlight'

# Pagination
gem 'kaminari'

#datetimepicker
gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.42'

# Geocode
gem 'geokit-rails'

# Icons
gem "font-awesome-rails"

# Models decorators
gem 'activemodel-serializers-xml', github: 'rails/activemodel-serializers-xml'
gem 'draper', github: 'audionerd/draper', branch: 'rails5'

# Redis
gem 'redis', '~> 3.0'

#Authentication with external social networks
gem 'therubyracer'
gem 'devise'
gem 'omniauth'
gem 'omniauth-google'


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-remote'
  gem 'pry-byebug' unless Gem.win_platform?
  gem 'pry-stack_explorer'

  gem 'erb2haml'

  gem 'letter_opener'

  gem 'rspec-rails'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'rails_real_favicon'

end

group :production do
  # Precompiles
  gem 'rails_12factor'

  # Images
  gem 'cloudinary'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
